### ISSUE TITLE
Clarification on identifier usage

### ISSUE THREAD

**Issue by AssetBurned** [marcveens/homebridge-device-alive#4]
Hi,

Could you clarify if only MAC address or IP address can be used, or if both can be used?
If it is the later one, what has priority? And what would happen if you have one device in the network that matches the IP but another that matches the MAC?

CU Assetburned ;-)

**Comment by marcveens** [comment]
Hi,

Only one of them can be used and it first looks for an IP match, and after that a MAC match. So if you do fill in both addresses, it will only use the match for the IP address. 

Did this answer your question?

**Comment by AssetBurned** [comment]
Yes thank you, might worth to put it in the docs?

**Comment by marcveens** [comment]
I updated the readme to make it more clear. Thanks for the suggestion!
